# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: DownloadSecureFile@1
  name: 'Publickey'
  inputs:  
    secureFile: 'azure_rsa.pub'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iac/azure'
    backendServiceArm: 'DevOps-k8s-ServiceConnection'
    backendAzureRmResourceGroupName: 'backend-rg'
    backendAzureRmStorageAccountName: 'tfpipelinestorage'
    backendAzureRmContainerName: 'mycontainer'
    backendAzureRmKey: 'k8.tfstate'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iac/azure'
    environmentServiceNameAzureRM: 'DevOps-k8s-ServiceConnection'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'